// Generated by protocol/companion/generate_fixtures.py; do not edit.

/// SHA-256 of the protocol generator, first 8 bytes. HELLO carries it; a peer
/// with a different value was built from a different protocol definition.
public enum ProtocolFingerprint {
    public static let bytes: [UInt8] = [0x4A, 0x94, 0x5E, 0x2B, 0x45, 0x23, 0x62, 0x38]
}
