// Generated by protocol/companion/generate_fixtures.py; do not edit.

/// SHA-256 of the protocol generator, first 8 bytes. HELLO carries it; a peer
/// with a different value was built from a different protocol definition.
public enum ProtocolFingerprint {
    public static let bytes: [UInt8] = [0xE7, 0xCE, 0xCD, 0xC7, 0x06, 0xF1, 0xCD, 0xCA]
}
