"""Generate the Home Micro 5 ASCII atlas (Pillow 12.3.0, font at the pinned SHA)."""
import argparse
import hashlib
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("font", type=Path)
parser.add_argument("output", type=Path)
args = parser.parse_args()
assert hashlib.sha256(args.font.read_bytes()).hexdigest() == "08a08c0d10129d2ecd869ff2f8914fcbf32487d3cbee3568b2a2957866dfdac8"
font = ImageFont.truetype(str(args.font), 36)
rows = []
widths = []
for code in range(32, 127):
    # Home uses an uppercase display label; stored HostProfile names are unchanged.
    char = chr(code).upper()
    mask = Image.new("1", (32, 36))
    ImageDraw.Draw(mask).text((0, 0), char, font=font, fill=1)
    widths.append(round(font.getlength(char)))
    data = mask.tobytes()
    rows.append("    {" + ", ".join(f"0x{b:02x}" for b in data) + "},")
args.output.write_text(
    "// Generated by scripts/generate_home_font.py; see README.md and OFL-micro5.txt.\n"
    "#pragma once\n#include <cstdint>\nnamespace cardputer_hub::apps::assets {\n"
    "inline constexpr std::uint8_t homeGlyphAdvance[] = {" + ", ".join(map(str, widths)) + "};\n"
    "inline constexpr std::uint8_t homeGlyphs[95][144] = {\n" + "\n".join(rows) +
    "\n};\n} // namespace cardputer_hub::apps::assets\n"
)
