"""Generate bounded PCM interface cues for AudioService.

Cue synthesis adapted from Codex Microputer ADV and modified for Cardputer Hub.
SPDX-License-Identifier: Apache-2.0
"""

import argparse
import math
from pathlib import Path


SAMPLE_RATE = 16_000
KEY_CLIP_LENGTH = 1_280
STEP_CLIP_LENGTH = 1_760
KEY_RELEASE_SAMPLES = 160
KEY_FREQUENCIES = (220.0, 233.0, 247.0, 233.0, 220.0, 247.0, 233.0, 220.0)
KEY_DECAY_SCALES = (1.00, 0.96, 1.03, 0.98, 1.02, 0.95, 1.01, 0.97)
TAU = math.tau
RAW_SCALE = 20_000.0
RAW_CEILING = 1.6
LOUDNESS_REFERENCE = 760.0
LOUDNESS_FLOOR = 280.0


def voice_gain(frequency: float) -> float:
    held_frequency = max(frequency, LOUDNESS_FLOOR)
    if held_frequency >= LOUDNESS_REFERENCE:
        return 1.0
    return (LOUDNESS_REFERENCE / held_frequency) ** 0.75


def trim_to_peak(samples: list[int], peak: float, target: float) -> list[int]:
    if peak <= 0.0001:
        return samples
    factor = target * 32_700.0 / (peak * RAW_SCALE)
    return [int(max(-32_700.0, min(32_700.0, sample * factor))) for sample in samples]


def key_clip(index: int) -> list[int]:
    body = KEY_FREQUENCIES[index]
    decay = KEY_DECAY_SCALES[index]
    noise = (0x2545F491 + index * 0x9E3779B9) & 0xFFFFFFFF
    previous_white = 0.0
    body_gain = voice_gain(body)
    second_gain = voice_gain(body * 2.01)
    third_gain = voice_gain(body * 3.02)
    peak = 0.0
    samples = []
    for sample_index in range(KEY_CLIP_LENGTH):
        time = sample_index / SAMPLE_RATE
        value = (
            math.sin(TAU * body * time) * math.exp(-time / (0.032 * decay)) * body_gain
            + math.sin(TAU * body * 2.01 * time)
            * math.exp(-time / (0.018 * decay))
            * 0.70
            * second_gain
            + math.sin(TAU * body * 3.02 * time)
            * math.exp(-time / (0.006 * decay))
            * 0.14
            * third_gain
        )
        if time < 0.004:
            noise = (noise * 1_664_525 + 1_013_904_223) & 0xFFFFFFFF
            white = ((noise >> 8) % 2_000 - 1_000) / 1_000.0
            dull = (white + previous_white) * 0.5
            previous_white = white
            value += dull * 0.20 * math.exp(-time / 0.0010)
        if time < 0.0005:
            value *= time / 0.0005
        release = min(1.0, (KEY_CLIP_LENGTH - 1 - sample_index) / KEY_RELEASE_SAMPLES)
        value *= release
        peak = max(peak, abs(value))
        samples.append(int(max(-RAW_CEILING, min(RAW_CEILING, value)) * RAW_SCALE))
    return trim_to_peak(samples, peak, 0.52)


def step_clip(notes: tuple[float, float]) -> list[int]:
    gain = tuple(voice_gain(note) for note in notes)
    octave_gain = tuple(voice_gain(note * 2.0) for note in notes)
    peak = 0.0
    samples = []
    for sample_index in range(STEP_CLIP_LENGTH):
        time = sample_index / SAMPLE_RATE
        value = 0.0
        for note_index, note in enumerate(notes):
            local_time = time - note_index * 0.038
            if local_time < 0.0:
                continue
            attack = min(1.0, local_time / 0.006)
            envelope = attack * math.exp(-local_time / 0.034)
            value += (
                math.sin(TAU * note * local_time) * 0.42 * gain[note_index]
                + math.sin(TAU * note * 2.0 * local_time) * 0.08 * octave_gain[note_index]
            ) * envelope
        peak = max(peak, abs(value))
        samples.append(int(max(-RAW_CEILING, min(RAW_CEILING, value)) * RAW_SCALE))
    return trim_to_peak(samples, peak, 0.62)


def array(name: str, clips: list[list[int]], clip_length: int) -> str:
    lines = [f"inline constexpr std::int16_t {name}[{len(clips)}][{clip_length}] = {{"]
    for clip in clips:
        lines.append("    {")
        for offset in range(0, len(clip), 16):
            values = ", ".join(str(value) for value in clip[offset : offset + 16])
            lines.append(f"        {values},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines)


def render() -> str:
    keys = [key_clip(index) for index in range(len(KEY_FREQUENCIES))]
    steps = [step_clip((659.25, 523.25)), step_clip((523.25, 659.25))]
    return (
        "// Generated by scripts/generate_audio_clips.py; see README.md.\n"
        "// Cue synthesis adapted from Codex Microputer ADV and modified for Cardputer Hub.\n"
        "// SPDX-License-Identifier: Apache-2.0\n"
        "#pragma once\n\n"
        "#include <cstdint>\n\n"
        "namespace cardputer_hub::services::audio_assets {\n\n"
        "// clang-format off\n"
        + array("keyClips", keys, KEY_CLIP_LENGTH)
        + "\n\n"
        + array("stepClips", steps, STEP_CLIP_LENGTH)
        + "\n// clang-format on\n\n"
        "} // namespace cardputer_hub::services::audio_assets\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not args.output.exists() or args.output.read_text() != generated:
            print(f"{args.output} is stale; regenerate it with {Path(__file__).name}")
            return 1
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
