# Writes the firmware build identity header. Runs on every firmware build (see
# main/CMakeLists.txt) and rewrites OUTPUT only when its content changes, so an
# unchanged identity does not recompile anything.
#
#   cmake -D SOURCE_DIR=<repo> -D OUTPUT=<header> -P write_build_identity.cmake
#
# CARDPUTER_HUB_BUILD_DATE (YYYY-MM-DD) and CARDPUTER_HUB_COMMIT override the
# local date and git commit, for reproducible release builds.

if(NOT DEFINED SOURCE_DIR OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "SOURCE_DIR and OUTPUT are required")
endif()

set(build_date "$ENV{CARDPUTER_HUB_BUILD_DATE}")
if(build_date STREQUAL "")
    string(TIMESTAMP build_date "%Y-%m-%d")
endif()

set(commit "$ENV{CARDPUTER_HUB_COMMIT}")
set(dirty "")
if(commit STREQUAL "")
    execute_process(
        COMMAND git rev-parse --short=7 HEAD
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE commit
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    execute_process(
        COMMAND git status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${SOURCE_DIR}"
        OUTPUT_VARIABLE changes
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    if(NOT changes STREQUAL "")
        set(dirty "+")
    endif()
endif()
if(commit STREQUAL "")
    set(commit "unknown")
endif()
string(SUBSTRING "${commit}" 0 7 short_commit)

set(content "// Generated by scripts/write_build_identity.cmake on every build.
#pragma once
#define CARDPUTER_HUB_COMMIT \"${commit}\"
#define CARDPUTER_HUB_BUILD_DATE \"${build_date}\"
#define CARDPUTER_HUB_BUILD_ID \"${build_date} ${short_commit}${dirty}\"
")

if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" existing)
    if(existing STREQUAL content)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${content}")
