// Generated by protocol/companion/generate_fixtures.py; do not edit.
// clang-format off
#pragma once

#include <array>
#include <cstdint>

namespace cardputer_hub::connectivity {

// SHA-256 of the protocol generator, first 8 bytes. HELLO carries it; a peer
// with a different value was built from a different protocol definition.
inline constexpr std::array<std::uint8_t, 8> companionProtocolFingerprint{
    0xE7, 0xCE, 0xCD, 0xC7, 0x06, 0xF1, 0xCD, 0xCA};

} // namespace cardputer_hub::connectivity
